### PR TITLE
Add a datdog link for hetzner machines

### PR DESCRIPTION
**Pull request by benhamad**
It would have been better to do it using the template language (server side), but it's a hassle to actually to provision the right env to test it.

### CODE REVIEW

**Comment by rbvermaa** [comment]
@Chakerbh This doesn't use the actual start/stop times right?

Also, what is the problem with setting up env? The README is pretty clear how to run locally?

**Comment by benhamad** [comment]
@rbvermaa It uses the time at which the build finished, but it doesn't use the time it started at (I'm defaulting that to 3 hours before the build finished and then users can change the time in Datadog accordingly)

Actually it seems the documentation seems to be lot better than last time I checked (couple years back 🙈). But not sure if adding startime is really worth the effort to use template instead of JS.

**Comment by rbvermaa** [comment]
It is worth it, imho. Users will expect the timeframe to be the same as the build. Also Datadog doesn't allow extending the timespan onec 'zoomed' in to a specific timeframe, so it will be hard for users to determine what time to use, when going back to e.g. last day, and then try to find the build time again.

**Comment by benhamad** [comment]
@rbvermaa Thanks, indeed hacking Hydra is much easier then what it used to be. I implemented the link in TT now and used the exact starttime and stoptime from the build step. The added benefit here, is that will work if you have multiple runs of the same builds (e.g. different builtsteps) which wasn't working in the JS version (only the latest build was considered)

**Review by rbvermaa — APPROVED** [review]

**Pull request merged**
